Add some missing steps to the guides
project-ncl/sbomer pull request #660
Opened 2024-08-16 21:59 UTC by dwalluck

Cover the commands for installing the following tools:

* gh
* minikube
* helm
* glab
* vault
* jq
* paas-encryption-cli
* tektoncd-cli (tkn)

2024-08-19 07:16 UTC, goldmann commented on docs/modules/developer-guide/pages/development-guide.adoc
> +GITLAB_HOST=gitlab.cee.redhat.com glab repo clone paas/paas-encryption-cli
I would not expose this here.

2024-08-19 07:44 UTC, goldmann requested changes
I have mixed feeling about this one:

1. It is Fedora-specific, I would probably refrain from it. For example I don't use Fedora. I would probably just mention tools and link to installation guides upstream.
2. I would remove any mentions of the security-related bits. Internal repository documentation can be provided by pointing (by the developers) to the `sbomer-helm` repository which contains some doc as well. This is not optimal, but at lest we don't leak how things are structured internally.
3. I would remove GitHub CLI and GitLab CLI instructions, these are very dependent on the developer preference/workflow (I don't use these).

2024-08-19 13:36 UTC, dwalluck commented
I have an idea. How about I provided a script like `./hack/install-prereqs-fedora.sh` that installs all required tools, then just make one brief mention of this and remove any direct mention from the docs.

2024-08-27 15:48 UTC, dwalluck commented
@goldmann Updated the docs. Added a script instead.

2024-09-16 14:05 UTC, vibe13 commented
I would also not mention anything specific related to the scripts in sbomer-helm. If anything is missing in the internal documentation, it should be there. Even if we leaked already something, we should not add anything more. Also, if you happen to change sbomer-helm, you would need to remember to update instructions here, which is harder to track.

Wrt Fedora instructions, I would add a sentence like " you need to install these packages etc etc", and then I am ok in saying that if you have Fedora, you can run the specific script etc etc. But I don't think we list everything required?

2024-09-27 12:49 UTC, goldmann requested changes
Hey @dwalluck, can you apply requested changes? I'll merge it afterwards.

2024-09-27 12:49 UTC, goldmann commented on docs/modules/developer-guide/pages/environment-setup.adoc
> +
Can you remove this paragraph?

2024-09-27 12:49 UTC, goldmann commented on hack/fedora-setup.sh
> +sudo dnf -y install tektoncd-cli
Can you remove this file?

2024-09-27 17:49 UTC, dwalluck commented on docs/modules/developer-guide/pages/environment-setup.adoc
> +
Done.

2024-09-27 17:49 UTC, dwalluck commented on hack/fedora-setup.sh
> +sudo dnf -y install tektoncd-cli
Done.

2024-09-27 18:06 UTC, merged